# Generated by Django 2.0.2 on 2020-02-29 08:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default=None, max_length=50, null=True)),
                ('feedback', models.CharField(default=None, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='coders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('pic', models.URLField(default=None, max_length=250, null=True)),
                ('location', models.CharField(default=None, max_length=50, null=True)),
                ('workType', models.CharField(default=None, max_length=100, null=True)),
                ('position', models.CharField(default=None, max_length=50, null=True)),
                ('industryType', models.CharField(default=None, max_length=100, null=True)),
                ('skillType', models.CharField(default=None, max_length=100, null=True)),
                ('email', models.EmailField(default=None, max_length=50, null=True)),
                ('github', models.URLField(default=None, max_length=250, null=True)),
                ('linkedin', models.URLField(default=None, max_length=250, null=True)),
                ('stackoverflow', models.URLField(default=None, max_length=250, null=True)),
                ('phone', models.CharField(default=None, max_length=50, null=True)),
                ('intro', models.CharField(default=None, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50, null=True)),
                ('industry', models.CharField(default=None, max_length=50, null=True)),
                ('location', models.CharField(default=None, max_length=50, null=True)),
                ('foundDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('companySize', models.CharField(default=None, max_length=50, null=True)),
                ('fundingType', models.CharField(default=None, max_length=50, null=True)),
                ('jobType', models.CharField(default=None, max_length=100, null=True)),
                ('intro', models.CharField(default=None, max_length=1000, null=True)),
                ('description', models.CharField(default=None, max_length=1000, null=True)),
                ('companyVisit', models.CharField(default=None, max_length=1000, null=True)),
                ('vision', models.CharField(default=None, max_length=1000, null=True)),
                ('teamMeeting', models.CharField(default=None, max_length=1000, null=True)),
                ('email', models.EmailField(default=None, max_length=50, null=True)),
                ('twitter', models.URLField(default=None, max_length=250, null=True)),
                ('linkedin', models.URLField(default=None, max_length=250, null=True)),
                ('facebook', models.URLField(default=None, max_length=250, null=True)),
                ('ins', models.URLField(default=None, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='experienceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default=None, max_length=50, null=True)),
                ('position', models.CharField(default=None, max_length=50, null=True)),
                ('field', models.CharField(default=None, max_length=50, null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('link', models.URLField(default=None, max_length=250, null=True)),
                ('detail', models.CharField(default=None, max_length=1000, null=True)),
                ('coder', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='user.coders')),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50, null=True)),
                ('teamMission', models.CharField(default=None, max_length=1000, null=True)),
                ('teamSize', models.CharField(default=None, max_length=100, null=True)),
                ('currentStage', models.CharField(default=None, max_length=1000, null=True)),
                ('qualification', models.CharField(default=None, max_length=1000, null=True)),
                ('work', models.CharField(default=None, max_length=1000, null=True)),
                ('teamCulture', models.CharField(default=None, max_length=1000, null=True)),
                ('contact', models.CharField(default=None, max_length=1000, null=True)),
                ('company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='user.company')),
            ],
        ),
        migrations.CreateModel(
            name='otherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('detail', models.CharField(default=None, max_length=1000, null=True)),
                ('coder', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otherInfo', to='user.coders')),
            ],
        ),
        migrations.CreateModel(
            name='projectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('field', models.CharField(default=None, max_length=50, null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('github', models.URLField(default=None, max_length=250, null=True)),
                ('detail', models.CharField(default=None, max_length=1000, null=True)),
                ('coder', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='user.coders')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='coder',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coder_appli', to='user.coders'),
        ),
        migrations.AddField(
            model_name='application',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_appli', to='user.company'),
        ),
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_appli', to='user.job'),
        ),
    ]
