# Generated by Django 2.0.2 on 2020-02-22 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('pic', models.URLField(default=None, max_length=250, null=True)),
                ('location', models.CharField(default=None, max_length=50, null=True)),
                ('workType', models.CharField(default=None, max_length=100, null=True)),
                ('position', models.CharField(default=None, max_length=50, null=True)),
                ('industryType', models.CharField(default=None, max_length=100, null=True)),
                ('skillType', models.CharField(default=None, max_length=100, null=True)),
                ('email', models.EmailField(default=None, max_length=50, null=True)),
                ('github', models.URLField(default=None, max_length=250, null=True)),
                ('linkedin', models.URLField(default=None, max_length=250, null=True)),
                ('stackoverflow', models.URLField(default=None, max_length=250, null=True)),
                ('phone', models.CharField(default=None, max_length=50, null=True)),
                ('intro', models.CharField(default=None, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='experienceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('field', models.CharField(max_length=50)),
                ('detail', models.CharField(default=None, max_length=1000, null=True)),
                ('coder', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='user.coders')),
            ],
        ),
        migrations.CreateModel(
            name='projectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('field', models.CharField(max_length=50)),
                ('detail', models.CharField(default=None, max_length=1000, null=True)),
                ('coder', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='user.coders')),
            ],
        ),
    ]
