# Generated by Django 2.2.10 on 2020-03-01 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experienceinfo',
            name='coder',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
        migrations.RemoveField(
            model_name='otherinfo',
            name='coder',
        ),
        migrations.RemoveField(
            model_name='projectinfo',
            name='coder',
        ),
        migrations.DeleteModel(
            name='application',
        ),
        migrations.DeleteModel(
            name='coders',
        ),
        migrations.DeleteModel(
            name='company',
        ),
        migrations.DeleteModel(
            name='experienceInfo',
        ),
        migrations.DeleteModel(
            name='job',
        ),
        migrations.DeleteModel(
            name='otherInfo',
        ),
        migrations.DeleteModel(
            name='projectInfo',
        ),
    ]
